using PagoPark.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using Colors = QuestPDF.Helpers.Colors;
using IContainer = QuestPDF.Infrastructure.IContainer;

namespace PagoPark.Tools;

public class ReportDocument : IDocument
{
    readonly string Title;
    readonly string Issued;
    readonly string DatetimeIssue;
    readonly WeekOrMontReport[] ReportItems;
    readonly string Observations;

    Tuple<DateTime, DateTime>? Week;
    DateTime? DateTimeMonth;
    int Year = 0;

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default;
    public DocumentSettings GetSettings() => DocumentSettings.Default;

    // for week
    public ReportDocument(string title, string issued, string datetimeissue, WeekOrMontReport[] reportitems, string observations, Tuple<DateTime, DateTime> week)
    {
        Title = title;
        Issued = issued;
        DatetimeIssue = datetimeissue;
        ReportItems = reportitems;
        Observations = observations;
        Week = week;
    }

    // for month
    public ReportDocument(string title, string issued, string datetimeissue, WeekOrMontReport[] reportitems, string observations, DateTime date)
    {
        Title = title;
        Issued = issued;
        DatetimeIssue = datetimeissue;
        ReportItems = reportitems;
        Observations = observations;
        DateTimeMonth = date;
    }

    // for year
    public ReportDocument(string title, string issued, string datetimeissue, WeekOrMontReport[] reportitems, string observations, int year)
    {
        Title = title;
        Issued = issued;
        DatetimeIssue = datetimeissue;
        ReportItems = reportitems;
        Observations = observations;
        Year = year;
    }

    public void Compose(IDocumentContainer container)
    {
        container
            .Page(page =>
            {
                page.Margin(25);
                page.Size(PageSizes.Letter);

                page.Header().Element(ComposeHeader);
                page.Content().Element(ComposeContent);

                page.Footer().AlignCenter().Text(x =>
                {
                    x.CurrentPageNumber();
                    x.Span(" / ");
                    x.TotalPages();
                });
            });
    }

    void ComposeHeader(IContainer container)
    {
        var titleStyle = TextStyle.Default.FontSize(14).SemiBold();

        container.Column(column =>
        {
            column.Item().Row(row =>
            {
                row.RelativeItem().Column(column =>
                {
                    column.Item().Text(Title).Style(titleStyle);
                    column.Item().Text($"Generated by {Issued}").SemiBold();
                    column.Item().Text(text =>
                    {
                        text.Span("Issue date: ").SemiBold();
                        text.Span($"{DatetimeIssue:d}");
                    });

                    if (Week is not null)
                    {
                        column.Item().Text(text =>
                        {
                            text.Span("Week: ").SemiBold();
                            text.Span($"{Week.Item1:d}");
                            text.Span(" to ");
                            text.Span($"{Week.Item2:d}");
                        });
                    }

                    if (DateTimeMonth is not null)
                    {
                        column.Item().Text(text =>
                        {
                            text.Span("Month: ").SemiBold();
                            text.Span(DateTimeMonth.Value.ToString("MMMM, yyyy").ToUpper());
                        });
                    }

                    if (Year > 0)
                    {
                        column.Item().Text(text =>
                        {
                            text.Span("Year: ").SemiBold();
                            text.Span(Year.ToString());
                        });
                    }
                });
            });
            column.Item().PaddingVertical(5).LineHorizontal(1).LineColor(Colors.Grey.Medium);

        });
    }

    void ComposeContent(IContainer container)
    {
        container.PaddingTop(10).Column(column =>
        {
            column.Spacing(5);

            column.Item().Element(ComposeTable);
            var totalPrice = ReportItems.Sum(x => x.TotalCollected);
            column.Item().AlignRight().Text($"Total: {totalPrice}$").SemiBold().FontSize(14);

            if (!string.IsNullOrWhiteSpace(Observations))
            {
                column.Item().PaddingTop(5).Element(ComposeObservations);
            }

        });
    }

    void ComposeTable(IContainer container)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(columns =>
            {
                columns.RelativeColumn(3);
                columns.RelativeColumn();
                columns.RelativeColumn();
            });

            table.Header(header =>
            {
                header.Cell().Element(CellStyle).Text("Contract");
                header.Cell().Element(CellStyle).AlignRight().Text("Absence");
                header.Cell().Element(CellStyle).AlignRight().Text("Amount");

                static IContainer CellStyle(IContainer container)
                {
                    return container.DefaultTextStyle(x => x.SemiBold()).PaddingVertical(5).BorderBottom(1).BorderColor(Colors.Black);
                }
            });

            foreach (var item in ReportItems)
            {
                table.Cell().Element(CellStyle).Text(item.Vehicle).FontSize(12);
                table.Cell().Element(CellStyle).AlignRight().Text(item.Absence.ToString()).FontSize(12);
                table.Cell().Element(CellStyle).AlignRight().Text(item.TotalCollected.ToString("0.00")).FontSize(12);
                static IContainer CellStyle(IContainer container)
                {
                    return container.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingVertical(5);
                }
            }
        });
    }

    void ComposeObservations(IContainer container)
    {
        container.Column(column =>
        {
            column.Item().Text(text =>
            {
                text.AlignCenter();
                text.Span("Observations").FontSize(14);
            });
            column.Item().Text(text =>
            {
                text.AlignLeft();
                text.Span($"{Observations}");
            });
        });
    }
}
